import type { Combination, GlobalParameters, Operation } from '@/types/pricing';

export const defaultGlobalParameters: GlobalParameters = {
  interest_rate: 12.5,
  storage_cost: 2.80,
  reception_cost: 3.50,
  desk_cost: 1.20,
  brokerage: 0.80,
  risk_premium: 1.5,
  soybean_volatility: 22,
  corn_volatility: 28,
  option_type: 'put',
  rounding: 2,
  soy_conversion_factor: 0.3674,
  soy_freight_premium: 8.50,
  corn_conversion_factor: 0.3937,
  corn_freight_premium: 6.20,
};

export const defaultCombinations: Combination[] = [
  {
    id: '1',
    commodity: 'soybean',
    display_name: 'Soja Paranaguá Mai/25',
    warehouse: 'Paranaguá',
    ticker: 'ZSK25',
    contract_price: 1042.50,
    maturity: '2025-05',
    payment_date: '2025-05-15',
    reception_date: '2025-04-20',
    sale_date: '2025-05-10',
    target_basis: -15.00,
    additional_discount: 2.00,
    override_interest_rate: null,
    override_storage_cost: null,
    override_reception_cost: null,
    override_desk_cost: null,
    override_brokerage: null,
    override_risk_premium: null,
  },
  {
    id: '2',
    commodity: 'soybean',
    display_name: 'Soja Rondonópolis Jul/25',
    warehouse: 'Rondonópolis',
    ticker: 'ZSN25',
    contract_price: 1058.25,
    maturity: '2025-07',
    payment_date: '2025-07-15',
    reception_date: '2025-06-20',
    sale_date: '2025-07-10',
    target_basis: -25.00,
    additional_discount: 3.50,
    override_interest_rate: null,
    override_storage_cost: 3.20,
    override_reception_cost: null,
    override_desk_cost: null,
    override_brokerage: null,
    override_risk_premium: null,
  },
  {
    id: '3',
    commodity: 'corn',
    display_name: 'Milho Cascavel Set/25',
    warehouse: 'Cascavel',
    ticker: 'ZCU25',
    contract_price: 472.00,
    maturity: '2025-09',
    payment_date: '2025-09-15',
    reception_date: '2025-08-20',
    sale_date: '2025-09-10',
    target_basis: -8.00,
    additional_discount: 1.50,
    override_interest_rate: null,
    override_storage_cost: null,
    override_reception_cost: null,
    override_desk_cost: null,
    override_brokerage: null,
    override_risk_premium: null,
  },
  {
    id: '4',
    commodity: 'corn',
    display_name: 'Milho Dourados Dez/25',
    warehouse: 'Dourados',
    ticker: 'ZCZ25',
    contract_price: 478.75,
    maturity: '2025-11',
    payment_date: '2025-11-15',
    reception_date: '2025-10-20',
    sale_date: '2025-11-10',
    target_basis: -10.00,
    additional_discount: 2.00,
    override_interest_rate: 13.0,
    override_storage_cost: null,
    override_reception_cost: null,
    override_desk_cost: null,
    override_brokerage: null,
    override_risk_premium: null,
  },
];

export const sampleOperations: Operation[] = [
  {
    id: 'op-001',
    created_at: '2025-03-20T14:30:00Z',
    commodity: 'soybean',
    display_name: 'Soja Paranaguá Mai/25',
    warehouse: 'Paranaguá',
    ticker: 'ZSK25',
    maturity: '2025-05',
    futures_price: 1042.50,
    exchange_rate: 5.08,
    gross_price_brl: 194.52,
    origination_price_brl: 168.30,
    purchased_basis_brl: -26.22,
    breakeven_basis_brl: -15.00,
    payment_date: '2025-05-15',
    sale_date: '2025-05-10',
    costs_snapshot: { net_costs: 26.22 },
    insurance_strategy: 'atm',
    insurance_premium_brl: 4.65,
    insurance_strike: 1042.50,
    volume: 500,
    operation_date: '2025-03-20',
    broker: 'Marex',
    account: 'ORIG-001',
    notes: 'Compra direta produtor região PR',
    status: 'open',
    pricing_snapshot: {} as any,
    legs: 'Futures: ZSK25 | NDF: USD/BRL @ 5.08 | Option: Put ATM',
  },
];
