// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwjiinullsasirrnuckm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13amlpbnVsbHNhc2lycm51Y2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNTY1NzksImV4cCI6MjA4OTkzMjU3OX0.42iyipMYmuTFX6sV0x_B5xgA2P6veVwUtBvaoacOsaw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});